services:
  database:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: VehicleManagementSystemDB
    ports:
      - "5432:5432" # Add this to expose PostgreSQL port
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - database

  server:
    build: .
    environment:
      DATABASE_URL: postgres://admin:admin123@database:5432/VehicleManagementSystemDB
    ports:
      - "8000:8000"
    depends_on:
      - database

volumes:
  postgres_data:
